### ISSUE TITLE
serialize and deserialize not support generic types

### ISSUE THREAD

**Issue by zqq90** [arangodb/java-velocypack#3]
Version: 1.0.11

Test source code: https://gist.github.com/zqq90/2aa2e7aa6fdd7453e50d26cb0bc22b30

Exceptions like:
```
Caused by: java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.GenericArrayTypeImpl cannot be cast to java.lang.Class
	at com.arangodb.velocypack.VPack.addValue(VPack.java:854)
	at com.arangodb.velocypack.VPack.serializeField(VPack.java:824)
	...
```

```
Caused by: java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.TypeVariableImpl cannot be cast to java.lang.Class
	at com.arangodb.velocypack.VPack.addValue(VPack.java:854)
	at com.arangodb.velocypack.VPack.serializeField(VPack.java:824)
	...
```

```
Caused by: java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.TypeVariableImpl cannot be cast to java.lang.Class
	at com.arangodb.velocypack.VPack.getValue(VPack.java:560)
	at com.arangodb.velocypack.VPack.deserializeCollection(VPack.java:597)
	...
```

**Comment by mvollmary** [comment]
same topic as https://github.com/arangodb/java-velocypack/issues/1

**Comment by zqq90** [comment]
please throw *Unsupport Exceptions* instead of `ClassCastException`

**Comment by mvollmary** [comment]
Added support for generic types in release 1.4.0. (Java driver includes this in release 5.0.0)
